CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 training/grpo_training.py \
    --model_name_or_path ./models/merged-sft-qwen25-7b \
    --train_file_dir data/grpo \
    --train_samples 20 \
    --max_steps 50 \
    --num_train_epochs 1 \
    --save_steps 25 \
    --save_strategy steps \
    --save_total_limit 2 \
    --output_dir outputs/outputs-grpo-qwen25-7b-v100-test \
    --dtype float16 \
    --fp16 True \
    --report_to tensorboard \
    --remove_unused_columns False \
    --gradient_checkpointing False \
    --beta 0.001 \
    --learning_rate 5.0e-7 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.03 \
    --use_vllm False \
    --logging_steps 1 \
    --use_peft True \
    --qlora False \
    --load_in_4bit False \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --num_generations 2 \
    --gradient_accumulation_steps 1 \
    --max_completion_length 512